# Generated by Django 6.0.1 on 2026-01-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_block_mandatory_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="isRecurring",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="block",
            name="specificDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
